[package]

name = "make-you-a-database"
version = "0.0.1"
authors = ["Jamie Brandon <jamie@scattered-thoughts.net>"]

[dependencies]
rand = "0.1"
time = "*"

[profile.bench]
lto = true

[profile.release]
debug = true